### PR TITLE
Aml parser

### PR DESCRIPTION
**Pull request by CWood1**
First stage of the AML interpreter project - AML grammar is parsed in its entirety, and an abstract syntax tree is built up from the parse.

### CODE REVIEW

**Comment by le-jzr** [comment]
It would be very useful if this was an independent crate, rather than tying it specifically to Redox.

**Comment by CWood1** [comment]
It's worth investigating, the problem is there are some instances where AML expects access to system memory; it's possible, for instance, to map in other ACPI tables into the AML namespace. That's a little difficult to do without access to the surrounding OS. Perhaps it might be worth considering as a stretch goal to the project, to be tackled at the end should time allow.

**Comment by le-jzr** [comment]
It should be fairly straightforward to turn the functions into methods on a generic struct, and extract the required OS functionality into a trait bound.

**Comment by jackpot51** [comment]
This has been merged. I had to squash and remove a few tilde files.

**Pull request closed without merging**
