### PR TITLE
Implementation of the IP loopback.

### PR DESCRIPTION
**Pull request by Yoric**
This patch lets users connect to `ip:127.0.0.1/*`. Bytes written to this connection can only be read from the same connection.

**Note**  I cannot build the entire kernel on my machine, so I could not test this.

### CODE REVIEW

**Comment by jackpot51** [comment]
Mostly OK - you should be reading from b in the test instead of a, which will fail because a shared VecDeque will have to be used.

I will merge as I expect the rewrite to address this problem.

**Comment by Yoric** [comment]
@jackpot51 I don't understand your comment about a shared `VecDeque`. Do you want me to change the implementation to use a shared `VecDeque`?

**Comment by jackpot51** [comment]
Say I use wget to download from 127.0.0.1, and httpd is providing 127.0.0.1:80

I will have two different IpResource's, each with an independent VecDeque, and they will fail to communicate.

Instead, it should be an Rc<RefCell<VecDeque>> that is defined on the IpScheme, allowing each loopback connection to read and write to the same queue

**Comment by Yoric** [comment]
Ok, I'll try and fix this immediately.

**Comment by jackpot51** [comment]
Thanks!

**Pull request merged**
