### PR TITLE
Pass relative, not canonicalized, path to script

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by jackpot51** [comment]
What is the purpose of this?

**Comment by ids1024** [comment]
This is the typical behavior; `argv[0]` (with either a script or executable) should be the name it was called with.

This `test.sh` script executed `./test.sh` should print `./test.sh` on both Linux and Redox:
```
#!/bin/sh
echo $0
```

**Comment by ids1024** [comment]
Before, that code was printing the canonicalized path.

**Comment by jackpot51** [comment]
Ok, cool

**Pull request merged**
