### PR TITLE
Allow for more complicated directory paths

### PR DESCRIPTION
**Pull request by cactorium**
This allows multiple ".." and "." parts to be used in a uncanonicalized path. Previously trying to access a path with "file:/home/user/../.." results in a ENOENT error, because that was canonicalized into "file:/home/..". This more correctly resolves the path to "file:". Unfortunately it adds another allocation, because I don't think it's possible to reverse an iterator unless it's backed in memory; there is probably a more efficient way to do this with more involved logic.

### CODE REVIEW

**Comment by cactorium** [comment]
Sorry, still verifying the changes I made in the last commit; have to rebuild Redox from scratch because I accidentally wrecked the submodule system

**Comment by cactorium** [comment]
It works now

**Comment by jackpot51** [comment]
Thanks for this! What sort of tests did you run? Would you like to add some tests to https://github.com/redox-os/acid?

**Comment by cactorium** [comment]
I opened up Ion and tried to do a bunch of cd's, like "../.." from the home directory, "cd /home/../bin/./../", etc. And I definitely will when I get back home! I was wondering where all the tests were...

**Pull request merged**
